### ISSUE TITLE
Test LDA on tweets to extract topics

### ISSUE THREAD

**Issue by lee-vivian** [CMU-IDS-2020/fp-mythbusters#1]

**Comment by jkosh44** [comment]
Python examples
- https://towardsdatascience.com/nlp-extracting-the-main-topics-from-your-dataset-using-lda-in-minutes-21486f5aa925
- https://medium.com/@soorajsubrahmannian/extracting-hidden-topics-in-a-corpus-55b2214fc17d 

Also look at foundations project 3 for example of text pre-processing

**Comment by jkosh44** [comment]
So I've been playing around with LDA a bit. It turns out that the output of the model isn't actually human readable topics. Each topic is a list of words and the weight for those words. For example when running it on a random sample of ~25,000 tweets I get the following topics

>Topic: 0 
Words: 0.031*"coronavirus" + 0.020*"https" + 0.014*"trump" + 0.011*"covid" + 0.008*"presid" + 0.007*"china" + 0.007*"realdonaldtrump" + 0.005*"american" + 0.004*"million" + 0.003*"invinc"

> Topic: 1 
Words: 0.021*"covid" + 0.018*"https" + 0.011*"pour" + 0.009*"dan" + 0.006*"coronavirus" + 0.005*"conflits_fr" + 0.005*"masqu" + 0.005*"confin" + 0.005*"tout" + 0.004*"admit"

> Topic: 2 
Words: 0.028*"covid" + 0.027*"https" + 0.027*"para" + 0.024*"coronavirus" + 0.009*"caso" + 0.008*"todo" + 0.007*"prueba" + 0.007*"persona" + 0.006*"sobr" + 0.006*"primer"

> Topic: 3 
Words: 0.019*"https" + 0.017*"covid" + 0.006*"kkmputrajaya" + 0.005*"todo" + 0.005*"coronavirus" + 0.005*"días" + 0.005*"malaysia" + 0.005*"sobr" + 0.004*"edselsalvana" + 0.004*"alguien"

> Topic: 4 
Words: 0.018*"https" + 0.012*"distanc" + 0.009*"social" + 0.008*"coronavirus" + 0.008*"go" + 0.006*"spend" + 0.006*"move" + 0.005*"stay" + 0.005*"strangeharbor" + 0.005*"surgica"

> Topic: 5 
Words: 0.017*"covid" + 0.013*"caso" + 0.010*"equip" + 0.009*"coronavirus" + 0.007*"president" + 0.007*"confirmado" + 0.006*"person" + 0.005*"poco" + 0.004*"arou" + 0.004*"silv"

> Topic: 6 
Words: 0.051*"covid" + 0.051*"https" + 0.025*"coronavirus" + 0.013*"peopl" + 0.007*"pandem" + 0.006*"time" + 0.006*"like" + 0.005*"help" + 0.005*"health" + 0.005*"need"

> Topic: 7 
Words: 0.030*"covid" + 0.027*"case" + 0.023*"coronavirus" + 0.020*"https" + 0.017*"test" + 0.011*"death" + 0.011*"report" + 0.008*"total" + 0.007*"number" + 0.007*"peopl"

> Topic: 8 
Words: 0.022*"coronavirus" + 0.019*"https" + 0.015*"covid" + 0.009*"conflits_fr" + 0.006*"franc" + 0.005*"mort" + 0.005*"plus" + 0.004*"sono" + 0.004*"prescrib" + 0.004*"plaquenil"

> Topic: 9 
Words: 0.008*"pelo" + 0.005*"moron" + 0.004*"llama" + 0.004*"minor" + 0.004*"scientifiqu" + 0.004*"avait" + 0.004*"https" + 0.004*"tota" + 0.004*"aplicación" + 0.003*"sake"

I don't honestly think this will be much use to us. Maybe we can just make a word bubble out of the tweet text instead.

**Comment by lee-vivian** [comment]
Yeah I agree. It might be best to just document the work you did in our report and say you tried LDA but we ultimately decided not to use it. Though a word bubble is a cool idea so maybe we can still use it. Is word bubble the same as word cloud?

**Comment by jkosh44** [comment]
Yes, sorry I meant word cloud
